name: Data Sync

on:
  push:
    paths: ['data/locations.json']
  schedule:
    - cron: '0 */6 * * *' # 每6小时保底同步
  repository_dispatch:
    types: [data_updated]


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch data
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} # 正确引用Secret
      run: |
        # 获取数据并保存为JSON
        curl -sH "Authorization: token $GH_TOKEN" \
          https://api.github.com/repos/Delitriuz/location-app/contents/data/locations.json | \
          jq -r .content | base64 -d > public/data.json

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add public/data.json
        git diff --quiet || (git commit -m "Auto-update data" && git push)
