name: Data Sync

on:
  # 手动触发（必须添加此行才会显示按钮）
  workflow_dispatch:
  # 自动触发条件：当 data/locations.json 文件变更时
  push:
    paths:
      - 'data/locations.json'
  # 可选：每天UTC时间8点自动同步
  schedule:
    - cron: '0 8 * * *'

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    # 步骤1：检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 步骤2：获取原始数据
    - name: Fetch and process data
      run: |
        # 安装必要工具
        sudo apt-get -yq install jq

        # 从GitHub API获取数据（需要仓库访问权限）
        curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/contents/data/locations.json | \
          jq -r .content | base64 -d > data.json

        # 验证生成的文件
        if [ ! -s data.json ]; then
          echo "错误：生成的文件为空"
          exit 1
        fi

    # 步骤3：提交变更
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git add data.json
        git commit -m "chore: auto-update data.json [skip ci]" || echo "没有变更需要提交"
        git push origin main

    # 权限配置（必须）
    permissions:
      contents: write
      pull-requests: write
